CREATE TABLE IF NOT EXISTS chiba.network_flows
(
    START_TIME UInt32,
    END_TIME   UInt32,
    SRCADDR    UInt32,
    DSTADDR    UInt32,
    DPKTS      UInt32,
    DOCTETS    UInt32,
    SRCPORT    UInt16,
    DSTPORT    UInt16,
    PROT       UInt8
) ENGINE = MergeTree() PARTITION BY toYYYYMMDD(toDateTime(START_TIME)) ORDER BY (START_TIME, SRCADDR, DSTADDR);
