CREATE MATERIALIZED VIEW IF NOT EXISTS chiba.metrics_mv
TO chiba.metrics
AS 
SELECT 
    toStartOfMinute(toDateTime(START_TIME)) AS BUCKET_TIME,
    SRCADDR,
    DSTADDR,
    sumState(toUInt64(DPKTS)) AS TOTAL_DPKTS,
    sumState(toUInt64(DOCTETS)) AS TOTAL_DOCTETS,
    DSTPORT
FROM chiba.network_flows
GROUP BY (BUCKET_TIME, SRCADDR, DSTADDR, DSTPORT);