CREATE VIEW IF NOT EXISTS chiba.global_metrics_view AS
SELECT 
    BUCKET_TIME,
    IPv4NumToString(SRCADDR) AS SRCADDR,
    IPv4NumToString(DSTADDR) AS DSTADDR,
    sumMerge(TOTAL_DPKTS) AS TOTAL_DPKTS,
    sumMerge(TOTAL_DOCTETS) AS TOTAL_DOCTETS,
    DSTPORT 
FROM chiba.metrics
GROUP BY (BUCKET_TIME, SRCADDR, DSTADDR, DSTPORT);
